### ISSUE TITLE
Encoding/decoding

### ISSUE THREAD

**Issue by dariusc93** [mongodb-labs/mongo-rust-driver-prototype#123]
Is there a way to encode/decode a struct to bson (or json to bson) for documents? I do know bson uses rustc serialize but I do not see any test or examples to perform such a task to make sure its done right (if its possible)

**Comment by kyeah** [comment]
Hey there! You can convert between json and bson using `bson.to_json()` and `Bson::from_json(json)`. You can see a small example of this in one of the [bson tests](https://github.com/zonyitoo/bson-rs/blob/master/tests/modules/bson.rs). 

Struct encoding and decoding would be functionality within the bson library, and there is actually an open pull request regarding this (https://github.com/zonyitoo/bson-rs/pull/7). However, instead of a roundabout `to_object` method, we would like a native Bson `Encoder` and `Decoder` similar to what is implemented for `Json` in rustc_serialize. Nobody is currently working on this as far as I'm aware, so feel free to tackle it!

**Comment by dariusc93** [comment]
Thanks @kyeah but how about converting bson to a document without having to create one and insert a key and value to it.
