### ISSUE TITLE
Plans for further development

### ISSUE THREAD

**Issue by thijsc** [mongodb-labs/mongo-rust-driver-prototype#130]
It seems like there is no active development on this driver at the moment, while that's not clear reading the readme for the project. I feel this situation makes people finding the C driver wrapper (https://github.com/thijsc/mongo-rust-driver) I wrote less likely.

The C driver wrapper is actually usable in production already, if there are no plans to finish this driver it seems like a more promising road forward for now.

Are there plans to turn this into a production ready driver? If not, could you clarify this in the Readme?

**Comment by vkarpov15** [comment]
"Production-ready" is a bit of a loaded term for MongoDB drivers, because that has business repercussions. I personally use this driver for production use cases and there's no reason I can think of why it isn't production-ready so long as you're using MongoDB 3.0.x. We'll put in some work to make sure this driver works correctly with MongoDB 3.2. However we can't suggest this is a fully-fledged production driver without internal approval, changing the official mongodb docs, etc. and there hasn't been enough demand for an officially-supported rust driver to justify this work.

**Comment by thijsc** [comment]
Thanks for the clarification. I think it would be good to add the Mongo 3.0 requirement to the readme, was not aware of that.

**Comment by vkarpov15** [comment]
https://github.com/mongodb-labs/mongo-rust-driver-prototype/commit/01fe6c6ad5865022427720197750591d067e07d8
