### ISSUE TITLE
SDAM test failing after update to submodule

### ISSUE THREAD

**Issue by saghm** [mongodb-labs/mongo-rust-driver-prototype#153]
After updating the `specifications` submodule, I noticed that one of the SDAM tests is failing. Specifically, the last phase of `rs/new_primary_new_setversion.json` is expecting a different set name for the server. From what I can tell, the set name given in the outcome for the server with hostname "a:27017" is not the same as it is in the response.

@kyeah, any idea if the error is due to a mistaken assumption on our part in terms of the test? I read through `https://github.com/mongodb/specifications/tree/master/source/server-discovery-and-monitoring/tests`, but I'm still not completely sure if something has changed in terms of the server responses or if our tests are just not handling this case properly.

**Comment by kyeah** [comment]
Looks like the SDAM logic has changed slightly to include setVersion fields. Previously we relied only on electionId to detect stale primary replies. On [this line](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/1.0/src/topology/mod.rs#L565), we check whether the electionId is _explicitly greater_ than the current max electionId, and accept the new primary if so.

In the last phase of the given test, the electionId from server A is `1`, which is equivalent to the electionId for primary server B. We therefore accept server A as the new primary, when it appears we should be looking at the setVersion and noticing that it is outdated.

We'll have to look into what's changed with SDAM and how it handles electionId vs. setVersion. We should also peruse the spec and make sure there aren't any new surprises since we've updated, although hopefully any new/updated tests will catch them for us.

**Comment by saghm** [comment]
Thanks for the explanation! I'll look into fixing the issue now that I understand what's going on.

There did seem to be other new tests in the spec repo, but none of them failed (although I should check to see if there were any new categories of tests, which would not have been picked up). The only other test failing for me right now is a GridFS one that I haven't had a chance to look into yet, but I hope to post an issue about it tonight if I can't fix it easily.

**Comment by saghm** [comment]
Just opened a PR to fix this; unfortunately a later test in the suite is also failing but wasn't showing before due to the entire suite being run as a single test case (I almost wish we could dynamically create test cases for each JSON file instead of having to use the test attribute on the entire suite...). I made sure that the PR isn't the cause of the later test failing by temporarily removing the test that it fixes and running the suite against the pre-PR code

**Comment by saghm** [comment]
My "fix" in #154 was not spec compliant, so I reimplemented that in #157. The SDAM tests should all work after #155, #156, and #157 are merged.
