### ISSUE TITLE
A number of tests fail on a freshly installed mongodb 3.2

### ISSUE THREAD

**Issue by lilianmoraru** [mongodb-labs/mongo-rust-driver-prototype#162]
I just installed MongoDB 3.2.9(Ubuntu 16.04 PPA) and cloned the repository.

I ran `cargo test` and it reported 11 failed tests, so I decided to re-run them with `RUST_BACKTRACE=1` to report them, and now I've got 13 failed tests.

I re-ran the tests with and without `RUST_BACKTRACE=1` a few times and seems that now it gives 13 fails every time. My guess would be that after the first run, it modifies something, don't know.

Here is the [full log](https://gist.github.com/lilianmoraru/79b8da9243407fc76a8fe37dd3c3e4d5).
Pay attention at:
```
test v3_0::auth::successful_login ... FAILED 
test v3_0::auth::invalid_password ... ok 
```
the first time, and then the second run:
```
test v3_0::auth::successful_login ... ok
test v3_0::auth::invalid_password ... FAILED
```

And the order is not kept of course(cargo).

**Comment by saghm** [comment]
There's no reason to run the `v3_0` tests on 3.2.9, as they pertain to 3.0.x versions of MongoDB. You can run the 3.2.x tests with `cargo test v3_2`.

Did you run the tests in parallel? The tests are designed to be run with a single thread, so if you didn't already, try running the tests with `RUST_TEST_THREADS=1` to see if that fixes the issues.

**Comment by lilianmoraru** [comment]
I ran only `v3_2` and 7 tests are failing without `RUST_TEST_THREADS=1` and 2 with `RUST_TEST_THREADS=1`(the tests ran considerably slower of course).

Here is the [full log](https://gist.github.com/lilianmoraru/81211ed8f3f89f210e2f2816a58d4ab2) for `v3_2`.

**Comment by saghm** [comment]
The five tests failing without the single-threaded testing are likely due to concurrent updates to the database (e.g. in `invalid_password`, another test has already created the same user). I'll take a look at the other two once I get a chance.

Thanks for letting us know!

**Comment by saghm** [comment]
Ah, okay, I think I figured out what's going on. The tests actually use two different databases, one running on the default port of 27017 and one running on 27018. The two tests that failed for you are the ones that use the second database. If you run a second mongod on this port (with a different dbpath), those two tests should pass.

I'm realizing now just how non-obvious it is to run our tests. Now that people are actually using the driver, I should probably add some documentation on how to run them. It also might be worth looking into seeing if the tests can be made to work in parallel, since a lot of them already are due to using different collection names.

I'm going to close this issue and open two new ones about the documentation for the tests and looking into making the tests parallelizable. Thanks so much for taking the time to try out our tests!
