### ISSUE TITLE
Bring This Driver To Production

### ISSUE THREAD

**Issue by Linicks** [mongodb-labs/mongo-rust-driver-prototype#165]
All,
  There are a number of new Rust users like me that would love to use MongoDB and Rust.  Rust has been stable for over a year, and there has been allot of polish since then.  It's unfortunate that Postgresql, and MySql are the few production options for Rust at the moment.

Thanks!
--Nick

**Comment by saghm** [comment]
Thanks, for the interest! Sorry we haven't been able to work much on it recently; this was originally an intern project that Kevin and myself worked on last summer, so we unfortunately haven't been able to put as much time into it as we were when we were working on it full time. There are a few outstanding issues that I totally could be working on in my free time though, so I'll try to put more effort into that in the coming weeks.

Are there any specific features that you are looking or that aren't available or outstanding bugs that we aren't currently aware of? I'd certainly love for this driver to be "production ready", but it's not clear to me what exactly that would entail. If you (or anyone else) have any specific thoughts on what could be done to expedite this, I'd love some feedback on that.

(Side note: keep in mind that this is in no way an officially supported MongoDB driver, and there aren't any plans to change that. While I definitely plan to keep working on it in my free time, it isn't maintained by MongoDB. This isn't to say that you shouldn't use it, but it's good to keep this in mind if you are going to us this in a production environment.)

**Comment by Linicks** [comment]
@saghm,  I wish there were more cooperate resource put into languages like Rust/Elixir/Haskell/ETC that give us above average safety so that we can spend less time on bugs that could have been avoided, but that's another topic :)  
  Unfortunately, I haven't spent enough time with the driver to have a solid feel of what's missing.  I've been holding off because of the Experimental Label.  I think that backing off a little on the  warnings may encourage users to jump in and use the driver.  Removing the "Experimental" tag, and just displaying a notice that this isn't an official driver is probably enough.   I've been to the project many times, but back off because of the flashing red lights.    Outside of that, we've moved over to Atlas and need features that allow us to utilize the service like TLS.  Naturally, all of typical features like connection pooling, etc, are needed to in busier production environments.  Some expanded docs would be helpful to get people jump started as well.  It seems like the first steps are the hardest. 
  Thanks for your work on this project, it's definitely appreciated!
--Nick

**Comment by saghm** [comment]
I think as far as advanced features go, most of it is already there; we've already implemented connection pooling, SDAM, GridFS, and SCRAM-SHA authentication, among other things. TLS is not yet implemented for the driver, although that's certainly something worth looking into.

Providing expanded documentation for how to use the driver is definitely a good idea. Even starting with something as simple as a list of implemented features would go a long way in helping people understand the current state of the driver.

One thing to note about the driver is that despite not being officially supported, it does follow the same specifications as the official drivers! This means that a lot of the usage should seem fairly familiar if you've used any of the official drivers. Obviously there will be differences due to the differences between the languages (e.g. the Rust driver using `Result` and `Error` types rather than throwing exceptions like the Python driver would), but the types and functions available are extremely similar to the other drivers.

As for the specifics of the language being used to describe the driver, I can look into it, but I don't think that is something that can be changed at this time. Given that the driver was written while Kevin and I were working at MongoDB and the code is hosted on a repository belonging to the MongoDB organization, we need err on the side of caution to make sure there isn't any confusion about the driver's affiliation to MongoDB.

That being said, I wouldn't let the label itself deter you from trying out the driver! Just because something is discouraged to use in production doesn't mean that it isn't usable for other things. I'd like to think it would be worth the time to try out for anyone who's interested in Rust and MongoDB, although obviously I'm a little biased :)

**Comment by ollivera** [comment]
@saghm I think @Linicks has a very good point. As you said above many important and advanced features are already implemented. We should promote this project, it would encourage people to use it.
This Prototype flag shouldn't last forever, official mongo driver or not.

**Comment by thijsc** [comment]
You could also take a look at https://github.com/thijsc/mongo-rust-driver. It wraps the official mongo c driver and is therefore mostly feature complete and stable.

**Comment by pyros2097** [comment]
Is the c based driver more performant? I guess it would be stable since it uses an official driver but the pure rust implementation makes it easy and also allows us to make changes for the future of rust when Futures or Promises finally come into rust and we can do asynchronous db calls which i guess the c driver wouldn't allow.

**Comment by kyeah** [comment]
From what I can recall via initial benchmarks, the C driver is more performant. The gap may have closed with improvements in the rust language and compiler, but my intuition is that the pure driver is hindered by the usage of Arc<Client>, the locking that occurs with (especially regarding topology monitoring), and areas where we clone objects unnecessarily. If anyone would like to do some rough benchmarking with the latest rust versions, please do :)

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!
