### ISSUE TITLE
Add TLS Connections

### ISSUE THREAD

**Issue by Linicks** [mongodb-labs/mongo-rust-driver-prototype#167]
All,
  As discussed in #165,  the ability to use TLS connections are necessary to use services like MongoDB ATLAS.  I'm not sure if the Tokio-TLS library (https://github.com/tokio-rs/tokio-tls), would help ease the implementation of this, but may be something worth exploring.  Tokio and Tokio-TLS were discussed at the 2016 Rust Conference in this presentation (https://www.youtube.com/watch?v=bcrzfivXpc4&index=4&list=PLE7tQUdRKcybLShxegjn0xyTTDJeYwEkI).  

Thanks!
--Nick

**Comment by saghm** [comment]
Thanks for the suggestion and the links! I'll try to look into this sometime this week

**Comment by saghm** [comment]
Hey! Sorry I've taken so long to work on this. I have a initial implementation that seems to be working, and I'd love to get some feedback on whether it works for you or not before I begin the process of merging it into the repo. It's currently hosted on a [branch of my fork of this driver](https://github.com/saghm/mongo-rust-driver-prototype/tree/ssl), so if you're up for helping me test it, you can clone and build that and try it out. In order to connect with SSL, you can create a [`ClientOptions` struct with the `with_ssl` method](https://github.com/saghm/mongo-rust-driver-prototype/blob/ssl/src/lib.rs#L198) and then create a client using those options with `Client::connect_with_options`. You'll have to have OpenSSL installed on the system you try his out on, as the driver is using the `openssl` crate to make the connection. Also, it's worth nothing that this has so far only been tested against a local `mongod` on my laptop and that we might change the API a bit before merging/pushing out a new version of the crate, so don't use this for anything super important.

If you're able to take some time to try this out, thanks so much! If not, thanks for bringing up the issue in the first place and all the feedback you've given us!

**Comment by saghm** [comment]
@Linicks not sure if you're still interested, but we just pushed version 0.2.0 with SSL support! Let me know if you have any questions about it.
