### ISSUE TITLE
Connect to a rights restricted mongos server topology

### ISSUE THREAD

**Issue by BlackYoup** [mongodb-labs/mongo-rust-driver-prototype#174]
Hi,

I'm having a few troubles with connecting to a mongodb server. I'm using a PaaS provider. The setup is the following: the DB is on a mongo "cluster" and in front of it, there is a mongos node. I don't have every rights on the mongos server. During my requests, I get rejected during the "isMaster" check because my user doesn't have access to the `local.is_master` function (I don't even know if it exists on a mongos).

Some logs:

```
COMMAND.find 195.154.243.92:27017 STARTED: { find: "projects", filter: {  }, projection: {  }, skip: 0, limit: 1, batchSize: 20, sort: {  } }
COMMAND.is_master 195.154.243.92:27017 STARTED: { isMaster: 1 }
COMMAND.find 195.154.243.92:27017 COMPLETED: { cursor: { id: 0, ns: "bo8guhscjyqn1p7.projects", firstBatch: [{ $err: "not authorized for query on bo8guhscjyqn1p7.projects", code: 13 }] }, ok: 1 } (71,489,783 ns)
COMMAND.is_master 195.154.243.92:27017 COMPLETED: { $err: "can't use 'local' database through mongos", code: 20 } (79,030,762 ns)
```

I found references here and there in the code about mongos but couldn't find an easy way to tell the driver that it connects to a mongos, so it doesn't have to check if the node is a master or not.

My knowledge of mongodb's architecture is quite low for now, don't hesitate to ask more details if I failed at my explanation.

Thanks !

**Comment by saghm** [comment]
I'm not positive, but it looks like you might need to authenticate yourself to the database? If you have a username and password provided, you can [authenticate to the database](https://docs.rs/mongodb/0.1.8/mongodb/db/trait.ThreadedDatabase.html#tymethod.auth), which might solve the issue you're having.

**Comment by BlackYoup** [comment]
Hi, thanks for the answer ! I tried before this weekend and it didn't work (got same output / error). Maybe I'm doing something wrong. I'll try to give you a code snippet but I'm lacking time these days :-/

**Comment by saghm** [comment]
I just re-read your original comment and realized that I'm not sure if you're connecting to the mongos or one of the mongod nodes. If you're connecting to a sharded cluster, you should be connecting to the URI of the mongos.

Assuming you're doing that, I'd probably need to see a code snippet like you suggested to try to help you debug this.

**Comment by BlackYoup** [comment]
Okay, here is a snippet: https://gist.github.com/BlackYoup/3cac9d6ef8f3cb6be09e6241956f7904
It logs commands in `/tmp/mongo-commands`

If I understood right, it's a sharded cluster with a mongos. So yes, technically I'm connecting to the mongos.

I use clever cloud ( https://www.clever-cloud.com/ ) to host this database, if you need credentials, tell me and I'll forward some to you.

Thanks for your time !

**Comment by saghm** [comment]
Thanks for the snippet! It looks like you're doing a bit more work than you need for the driver, so I condensed your snippet down a bit. Any chance you could try [this one](https://gist.github.com/saghm/c90d9178975a77caa8b6eeb0f7955a29) out with your connection and authentication info and give me the output (both from the command line and the logfile)?

**Comment by BlackYoup** [comment]
Seems like it worked ! So, was it my driver use that was wrong or the `ConnectionString` should have worked with the user / password ?

**Comment by saghm** [comment]
Awesome! I'm glad it's working.

My best guess of why it wasn't working is an incorrect specification of the topology; in general, it's better to just give the client the connection info for one of the hosts and let it automatically discover the topology, since otherwise you could specify the topology incorrectly. In this case, it looks like that might have happened, as you specified the topology type as "single" when it should have been "sharded".

Adding the username and the password to the connection string was unnecessary in this case, as the driver lets you authenticate through the `auth` method, but I don't think it causes any issues. If you're curious, you can try this out by changing the call to `connect_with_options` to [`with_uri_and_options`](https://docs.rs/mongodb/0.1.8/mongodb/trait.ThreadedClient.html#tymethod.with_uri_and_options) and manually specifying the URI including the username and password.

Thanks for using our driver! If you have any other questions about proper driver usage, feel free to open another issue, and we'll try to help you out as soon as we can.
