### ISSUE TITLE
Excessive delay in cursor::Cursor::count

### ISSUE THREAD

**Issue by rcastill** [mongodb-labs/mongo-rust-driver-prototype#176]
Hi!,

I do not know if there is an implementation issue with `count()` from iterator, but doing some tests it took too long to perform the operation to certain query, whilst it is almost instantaneous in python or Javascript.

Has this been noticed yet?

**Comment by saghm** [comment]
Any chance you could post a small example of code (and possibly database contents, if you can replicate it with a small example of non-confidential data)? There is no `Cursor::count` method, so I want to make sure I understand the issue that you're having.

**Comment by rcastill** [comment]
This is the relevant code:

```rust
let dt = chrono::UTC::now();

let cursor = mongo_client.db("CIA-secret-database")
    .collection("coups-detat")
    .find(Some(doc! {
        "timestamp" => {
            "$lt" => dt
        }
    }), None).unwrap();

println!("{}", cursor.count());
```

I run it like this:

```shell
$ time cargo run
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/json-tests`
92330

real	0m13.356s
user	0m8.892s
sys	0m4.010s
```

And finally, these are my dependencies:

```toml
bson="0.3.2"
mongodb="0.1.8"
chrono="0.2"
```

Thanks in advance!

**Comment by saghm** [comment]
This appears to be calling [`Iterator::count`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.count), which `Cursor` gets from the `Iterator` trait in the standard library. Judging from the fact that you're comparing the performance to other drivers, I'm guessing you're looking for [`Collection::count`](https://docs.rs/mongodb/0.1.8/mongodb/coll/struct.Collection.html#method.count). Try changing the code to the following and see if that helps:

```rust
let dt = chrono::UTC::now();

let count = mongo_client.db("CIA-secret-database")
    .collection("coups-detat")
    .count(Some(doc! {
        "timestamp" => {
            "$lt" => dt
        }
    }), None).unwrap();

println!("{}", count);
```

**Comment by kyeah** [comment]
Hey @rcastill! `count` is an instance variable, so the call itself should be instant. Can you time the `find` call itself? 

The work on this driver hasn't been too active and the latency issues are a known problem; this is likely due to extensive locking that occurs to periodically check on and update the server topology. Additionally, the first network request may take longer to complete since you're establishing a connection, so if this is the first request, it will take longer — timing a followup call can shed some light on how long the `find` call takes vs. connection establishment.

cc. @saghm, this brings up a discrepancy I noticed in the `count` for the Rust cursor and that for other drivers. [The Rust driver](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/9d2ab4bbc908b085f8436393466f11ad103bc89b/src/cursor.rs#L51) is a field that describes the number of results that have been iterated over already, while [other drivers](https://github.com/mongodb/mongo-python-driver/blob/c0767a551ac38fb8b630214bbf20368951e7609f/pymongo/cursor.py) have an explicit function that returns the entire collection count/size. This seems like something we should match — if we'd still like to have our version of `count`, we should rename the field to something more descriptive, perhaps `seen`.

**Comment by saghm** [comment]
> Hey @rcastill! count is an instance variable, so the call itself should be instant. Can you time the find call itself?

I don't think this is the case; count is a private variable. I'm still pretty sure this is calling `Iterator::count`.

**Comment by kyeah** [comment]
Ah sorry for the hot take!

In this case it depends entirely on your collection size, as our cursor is paginated and will require a series of calls to consume the iterator. We'd need to customize this method to make a definitive number of calls.

**Comment by saghm** [comment]
I think the confusion between our cursor API and that of other drivers is due to other drivers mimicking the behavior of the shell, where `foo.find(...).count()` is equivalent to `foo.count()`. I'm guessing behind the scenes this is done by lazily loading the first item returned by the cursor, and in the case that a method like `count()` is called before `next()` is called, immediately fetching all the results (possibly with an increased batch size to reduce the number of network calls) and returning the count. I'd be a bit hesitant to implement something like this for our driver though; `Iterator::count` returns a `usize`, and there isn't any way to override it to return a `Result<usize>`. Because of this, calling `count()` on a cursor ignores any errors that occur when fetching additional batches, so I think it would be better to encourage usage of `Collection::count`.

One way to make the query API more similar to that of other drivers would be to use the builder pattern as an alternative to using the options struct for options like limit, sort, count, etc. I'd envision this looking something like `let cursor = coll.find(...).limit(5).sort(doc! { "x" => -1 }).send()?;`. The benefits of this would be that it's more intuitive to users familiar with other driver and that it would eliminate the need for an options struct for what I'd assume is a rather large portion of the common use cases. The main downside would be the need for a `send()` in order to actually send the query. I'm a little mixed about whether this would be a good idea; while it would arguably be more idiomatic Rust and would resemble a few of the drivers a bit more, I'm not convinced that it's worth it when it would force every single query to append an extra method at the end, especially given how this would end up diverging the API from other drivers, which was the initial problem this was trying to fix in the first place. I think supplying arguments to queries in this way is probably only going to end up looking like "idiomatic Mongo", for lack of a better term, in dynamic languages that wouldn't run into this issue.

**Comment by rcastill** [comment]
Yes, I'm referring to `Iterator::count`, I actually thought you've manually implemented it for the trait.

I tried what you recommended and it worked flawlessly. Thanks for the support, maybe it would be a good idea to override `Iterator::count` after all.

**Comment by saghm** [comment]
> I tried what you recommended and it worked flawlessly.

Awesome!

> maybe it would be a good idea to override Iterator::count after all

For the reasons I mentioned above, I'd be a little hesitant to do so. TLDR: There's no way to override `Iterator::count` to return `Result<usize>` rather than `usize`, so I think it's better to discourage using `Iterator::count` as a replacement for `Collection::count`.

**Comment by rcastill** [comment]
Got it. Totally agree.

**Comment by saghm** [comment]
I'm going to close this issue now. Thanks for the feedback on the driver, and feel free to open new issues if you have any other questions or suggestions!
