### ISSUE TITLE
Use mongo-orchestration for testing 

### ISSUE THREAD

**Issue by kyeah** [mongodb-labs/mongo-rust-driver-prototype#189]
Setting up multiple databases is tedious, especially when adding new version support. As @saghm mentions, we can do a lot better here.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!
