### ISSUE TITLE
Investigate r2d2 for connection poolilng

### ISSUE THREAD

**Issue by kyeah** [mongodb-labs/mongo-rust-driver-prototype#191]
We should investigate [r2d2](https://github.com/sfackler/r2d2) for connection pooling and see if that gives us any performance benefits, and if so, whether there are any downsides to switching.

**Comment by saghm** [comment]
Without having had to chance to actually look into the library, the name of it alone already puts it at an advantage in my mind.

**Comment by mexus** [comment]
Hi guys!

Any plans on implementing that feature? It might be very useful for real-world applications. Could it be that you lack on resources and some help might be used? :)

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!
