### ISSUE TITLE
Add default and Clippy lints to build process

### ISSUE THREAD

**Issue by kyeah** [mongodb-labs/mongo-rust-driver-prototype#194]
Let's settle on some must-have lints and pull them into the build process. [travis-cargo](https://github.com/huonw/travis-cargo) might be helpful for running clippy, since it relies on nightly.

see this discussion for context: https://github.com/mongodb-labs/mongo-rust-driver-prototype/pull/192#discussion_r103093236

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!
