### ISSUE TITLE
Use the new tokio service library?

### ISSUE THREAD

**Issue by pyros2097** [mongodb-labs/mongo-rust-driver-prototype#196]
Will it be possible tokio service as the underlying transport to implement asynchronous operations? I actually wanted to try to see if it was possible to do asynchronous web-applications in rustlang now.
https://github.com/housleyjk/ws-rs/issues/111
https://docs.rs/tokio-postgres/0.2.1/tokio_postgres/

**Comment by kyeah** [comment]
hi! this isn't possible at the moment, but it's definitely on our radar, and we'd love to have asynchronous support for the driver.

At the moment, a single method call prepares, executes, and parses results. Looking at other languages, most mongodb drivers have two separate versions (sync and async) which share common code. It remains to be seen whether it's possible to generalize the current driver and provide easy support for both.

It's a big change, but I'd love to see some initial work on this in the future.

**Comment by thedodd** [comment]
@kyeah so, just a quick update in response to the above comment. The library could be coded to use futures, on top of the tokio stack &c, and then if a user needs it to be sync, they can just call `.wait()` on the future. 

I know that there would be a pretty serious amount of work which would need to go into getting things cut over to tokio & futures, but a single futures based approach would cover both cases quite well.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
