### ISSUE TITLE
Use derive_builder for Options structs

### ISSUE THREAD

**Issue by kyeah** [mongodb-labs/mongo-rust-driver-prototype#197]
A lil tracking issue to use `derive_builder` for our options structs. See [this comment](https://github.com/mongodb-labs/mongo-rust-driver-prototype/pull/183#issuecomment-275822133) in 183 for discussion.

**Comment by saghm** [comment]
It seems like https://crates.io/crates/typed-builder is getting popular and doesn't have the issue that `derive_builder` has with requiring a `Result` to be returned from the builder method in all cases, so I think we should use that when we implement this feature.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
