### ISSUE TITLE
Find Fail

### ISSUE THREAD

**Issue by Matrix-Zhang** [mongodb-labs/mongo-rust-driver-prototype#206]
i have a document such as:
``` 
{
    "_id" : ObjectId("xxxxx"),
   "addresses": [
      { "detail": "00000" },
      { "detail": "11111" }
   ]
}
```
if the find filter is
```
doc! { "_id" => ObjectId("xxxxx"), "addresses.detail": "00000" }
```
it return none but is mongo-shell is ok

**Comment by saghm** [comment]
How exactly are you creating the ObjectId? It doesn't look like the code sample you've given using the `doc` macro will compile, since `Bson::ObjectId` only takes an `ObjectId` struct, not a string. Assuming you want to create the the ObjectId from string, you'll need to use `ObjectId::with_string`, which works locally for me when I try out your example.

**Comment by Matrix-Zhang** [comment]
meybe i have somnambulated.... it's ok now....
