### ISSUE TITLE
How to set pool size for my client?

### ISSUE THREAD

**Issue by YjyJeff** [mongodb-labs/mongo-rust-driver-prototype#213]
Hi, I find that the default pool size is 5. I think it's too small. How can I set the pool size ? 
Thanks in advance!

**Comment by saghm** [comment]
Thanks for filing the issue! It actually looks like we don't currently have a publicly accessible way of doing this right now, so we'll need to fix that!

 @kyeah, should we add an option to `ClientOptions` and pass that through all the way through to `ConnectionPool::with_size`?

**Comment by kyeah** [comment]
yep, that would be the way to go here! feel free to assign yourself if you're thinking of picking up this issue 🙏

**Comment by saghm** [comment]
Will do! I have a train ride tomorrow that's a few hours long, so I might take a look at it then

**Comment by saghm** [comment]
Hi! I just wanted to give an update on this since it's been a while without any visible progress on this. Upon looking into the client pooling in the driver, I found that there were some mistakes in the design that caused more clients than expected to be created (with the excess ones not being accessible to the user and therefore being dead weight), and we've decided to try to rewrite the connection pooling to use [r2d2](https://crates.io/crates/r2d2), which has built in support for setting a custom pool size. The first step in this work is #218, although we'll need at least one more PR to complete this work.

Let me know if you have any questions about all this!

**Comment by saghm** [comment]
The pool size determines the number of connections that are able to be open to a given server at once.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
