### ISSUE TITLE
Seemingly unable to connect via SSL due to missing function

### ISSUE THREAD

**Issue by rjcoupe** [mongodb-labs/mongo-rust-driver-prototype#226]
Trying to follow the docs:

```
extern crate mongodb;
use mongodb::{Client, ClientOptions, ThreadedClient};
let options = ClientOptions::with_ssl(None, None, None, false); // Bare bones, thoroughly untrustworthy SSL connection
```

But I get the following error:
```
error[E0599]: no function or associated item named `with_ssl` found for type `mongodb::ClientOptions` in the current scope
```

I'm brand new to Rust, so there's every chance I'm missing something stupid here, but I can't see what ..

**Comment by saghm** [comment]
Hi! Is is possible that you're not compiling with the "ssl" feature enabled? Since the driver needs to link to OpenSSL to be able use SSL and some systems might not have it installed, the SSL features are disabled by default. You'll need to add `--features ssl` to your Cargo invocations (build, run, etc.) if you haven't already.

Once you compile with the SSL feature, I think your current code will still fail to compile, as the parameters of `ClientOptions::with_ssl` are not options. In Rust, `None` is of type `Option<T>` (where `T` is a generic parameter"), so it can't be used for anything that isn't an `Option`, like the `&str` type of the first three parameters of the `with_ssl` function. However, from looking at the generated documentation on docs.rs, it looks like this function is missing! I believe that this is due to docs.rs not generating documentation for the code that is only conditionally compiled when the "ssl" feature is enabled. I'm going to open a new issue for right afters I submit this comment.

Let me know if anything I've said here isn't clear, or if you have any other questions about the driver!

**Comment by rjcoupe** [comment]
Hi @saghm - I tried adding `--features ssl` but ran into an error stating that my package does not have that feature. I'm running OSX and have OpenSSL 0.9.8 installed, so I'm presuming I need to explicitly make it available to Rust, somehow? Thanks for your help!

**Comment by saghm** [comment]
Are you still having trouble with this, or have you gotten it working?

**Comment by saghm** [comment]
I'm going to close this issue since we haven't heard from you in a bit. Feel free to reopen it or file a new issue if you're still having trouble.
