### ISSUE TITLE
cursor to JSON example or method

### ISSUE THREAD

**Issue by greenpdx** [mongodb-labs/mongo-rust-driver-prototype#233]
I have am new with rust, and I want to bulk transfer a "cursor" to a webpage using JSON.  I feel this is very important for mongo to be used in web applications using rust as the server.  
I have gotten this far, and I understand how to grab specific keys and values from document, and I can turn docs into a byte stream, but I do not know how to turn doc into JSON.

          let docs : Vec<_> = cursor.map(|doc| doc.unwrap()).collect();

I expect I could use the above code with  
          doc.unwrap().map(|itm| itm.DOSOMETHING())
   or
          tojson(doc.unwrap())

Please help.

**Comment by saghm** [comment]
Hi! The `Bson` type implements `Into<serde_json::Value>`, so if you add `serde_json` as a dependency and `use serde_json::Value`, you can just use the `into()` method to convert it.

As for sending it to a webpage, though, this might not be the right route to go. Most often you'll be using some sort of backend framework to serve your app, so it's probably better to just send the data in whatever format it supports (e.g. taking the data out of the documents and passing them to a template renderer or to build a rest API with your backend framework and have your frontend framework use that to get the data rather than directly from the database). If you decide that you do want to send the results directly to the frontend, you could convert to JSON and then use serde_json's functionality to convert it into a string to send, but I'd definitely give the other options some thought first.

**Comment by greenpdx** [comment]
I understand what you are saying, but I pass a large data set to the front-end and do real-time  data analysis / display in the front end.  I am using Vue as the SPA framework,  so I only use JSON data as communication between the rust server and front end. I am transferring about 5K documents each 2K (about 1M compressed of JSON).  That is why I want to keep the back-end quick.     
Would it be possible to write a snippet of code that transforms the cursor in to a JSON  string?  
I will write a rust REST back-end for the other data requirements..
see http://taxnvote.org to see the SPA. The 3D and tree is a subset of the data.

**Comment by saghm** [comment]
Ah, makes sense! Here's an example of a function to convert a cursor into a serde_json::Value (along with a main function to demo its usage):

```rust
extern crate bson;
extern crate mongodb;
extern crate serde_json;

use bson::Bson;
use mongodb::{Client, ThreadedClient, Result};
use mongodb::db::ThreadedDatabase;
use mongodb::cursor::Cursor;
use serde_json::Value;

fn json_value_from_cursor(cursor: Cursor) -> Result<Value> {
    let jsons: Result<Vec<Value>> = cursor
        .map(|doc| {
            let json: Value = Bson::Document(doc?).into();
            Ok(json)
        })
        .collect();

    Ok(jsons.map(Value::Array)?)
}

fn main() {
    let client = Client::connect("localhost", 27017).unwrap();
    let db = client.db("foo");
    let coll = db.collection("bar");
    let cursor = coll.find(None, None).expect("Unable to execute query");
    let json = json_value_from_cursor(cursor).expect("Unable to receive all documents from cursor");

    println!("{}", json);
}
```

Note that the cursor API iterates over document results rather than just documents; this is because the driver fetches each batch of results lazily, so in the case of multiple round trips, there might be an error getting the next document even if all the previous ones were fetches successfully. Luckily, the `Result` type implements `Iterator`, so we can collect into `Result<Vec<T>` from an iterator over `Result<T>`,  so we just have to map the `Result<Document>`s into `Result<serde_json::Value>`s, which is fairly straightforward due to `From<Bson>` being implemented for `Value`. Finally, we just need to wrap the `Vec<Value>` in a `Value::Array` and return that if no error occurs.

Let me know if you have any questions about the above code! It can be tricky to follow if you're not experienced with Rust's iterators and results.

**Comment by greenpdx** [comment]
Thanks, Looking at the code I understand it, but I could not write it.
 The full project will be at github.com/greenpdx/tnvvue, the rust server will be a submodule.

**Comment by saghm** [comment]
If it helps at all, feel free to lift the function for converting the cursor to JSON for your project. And feel free to file another issue if you have any other questions!
