### ISSUE TITLE
Document to struct and back that has binary data

### ISSUE THREAD

**Issue by greenpdx** [mongodb-labs/mongo-rust-driver-prototype#234]
I am trying to save and retrieve crypto data in a mongo collection.  I managed to create a code mess to do it.  Before I insert and after a find, I convert the binary data to base64 string.  I have pasted my structure, From implementation and document.  I am not happy with the code, as you can see why.  

Is there a way to write binary to mongo using rust?       
What can I do to clean up the code?
How do I handle errors?  there are 12 unwrap()
I can not find any examples of mongo dealing with structures, am I doing it the correct way?

```rust
#[derive(Debug)]
struct TmpLogin {
  sess: PublicKey,
  addr: String,
  ts: i64,
  prekey: PrecomputedKey,
  nonce: Nonce,
}
  
impl From<Document> for TmpLogin {
  fn from(doc: Document) -> TmpLogin {
    let nonce: &[u8] = &decode(doc.get_str("nonce").unwrap()).unwrap();
    let sess: &[u8] = &decode(doc.get_str("sess").unwrap()).unwrap();
    let val = TmpLogin {
      sess: PublicKey::from_slice(sess).unwrap(),
      addr: doc.get_str("addr").unwrap().to_string(),
      ts: doc.get_i64("ts").unwrap(),
      prekey: PrecomputedKey::from_slice(&decode(doc.get_str("prekey").unwrap()).unwrap()).unwrap(),
      nonce: Nonce::from_slice(nonce).unwrap(),
    };
    println!("FROM {:?} {:?}", doc, val );
    val
  }
}
```

 OrderedDocument({"_id": ObjectId(ObjectId(59a4967c3732382d788aa61e)), "sess": String("NHwCJgP8KZ3ErCPYbH6TkA+hE/rlEANBKkVjm2+9VjY="), "addr": String("10.0.42.126"), "ts": I64(1503958652), "prekey": String("ect+TYPu1WndhoL5IUnU7N4G1aDYv+TseXjYy7vOn4s="), "nonce": String("tcvm+hE5Gv6GDSM/XLHlJfdtlzWw8Sxi")})

**Comment by saghm** [comment]
This is currently a wart in the Rust language; the idiomatic way to deal with this would be to implement `From<Document> for Result<TmpLogin, ...>`, but since both Result and Document are defined in external crates, this wouldn't compile. The proposed solution for this is the [`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) trait, but unfortunately it's still unstable. Assuming that you're not doing any automatical serialization/deserialization with serde (which it looks like you're not), the best solution is probably to just implement an `into_document` method directly on TmpLogin that returns a Result.

**Comment by greenpdx** [comment]
I found some good docs that helped on bson-rs website.  One of the problems I am having is find the correct docs. As you stated earlier that returns are difficult.  I would suggest that on the frist page you would add a example of a structure being read inserted and find into mongodb with a result being returned. the examples using println does not help with returns.

If there is an easier way I would love to learn it

the structure
```rust
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Person {
  email: String,    // EMail
  salt: String,
  pass: String,
  fname: String,
  lname: String,
  age: i8,
  wealth: i8,
  fiscal: i8,
  social: i8,
  role: i32,
  id: String,
  first: i64,
  last: i64,
}
```
convert struct to bson
```rust
  pub fn to_bson(&self) -> Document {
    let doc = doc! {
      "email" => (&self.email),
      "fname" => (&self.fname),
      "lname" => (&self.lname),
      "salt" => (&self.salt),
      "pass" => (&self.pass),
      "age" => (self.age as i32),
      "wealth" => (self.wealth as i32),
      "social" => (self.social as i32),
      "fiscal" => (self.fiscal as i32),
      "id" => (&self.id),
      "first" => (self.first),
      "last" => (self.last)
    };
    doc
  }
}
```
Document to struct

```rust
impl From<Document> for Person {
  fn from(doc: Document) -> Person {
    let person = Person {
      email: doc.get_str("email").unwrap().to_string(),
      fname: doc.get_str("fname").unwrap().to_string(),
      lname: doc.get_str("lname").unwrap().to_string(),
      salt: doc.get_str("salt").unwrap().to_string(),
      pass: doc.get_str("pass").unwrap().to_string(),
      age: doc.get_i32("email").unwrap() as i8,
      wealth: doc.get_i32("email").unwrap() as i8,
      social: doc.get_i32("email").unwrap() as i8,
      fiscal: doc.get_i32("email").unwrap() as i8,
      role: doc.get_i32("role").unwrap(),
      id: doc.get_str("id").unwrap().to_string(),
      first: doc.get_i64("first").unwrap(),
      last: doc.get_i64("last").unwrap(),
    };
    person
  }
}
```

**Comment by saghm** [comment]
Thanks for the feedback! I believe that the reason this doesn't feature prominently in the documentation for this driver because at the time when the driver was initially written, the bson crate was using rustc-serialize rather than serde, and we assumed the standard way users would use the driver would be through manual use of the bson crate's types. It's probably worth at least pointing out the bson crate's documentation about automatic serialization/deserialization features somewhere in our docs, though.

**Comment by armizimm** [comment]
hi everyone,
i'm try this, but i'm get a error when i try convert vector:

      let vec1 = vec!( "a","b","c");
      let doc = doc!{ "vector" : (&vec1) };
----------------------------------------------------------
let doc = doc!{ "vector" : (&vec1) };
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<&std::vec::Vec<&str>>` is not implemented for `mongodb::Bson`
