### ISSUE TITLE
Only returning a limited number of items and locks

### ISSUE THREAD

**Issue by cedricve** [mongodb-labs/mongo-rust-driver-prototype#240]
Hey,

I've been experimenting with this library, but it looks that when trying to iterate over a collection I only get a few items returned and afterwards the program goes in a locked state. Also when trying to find a record which is at the end of the collection, the program locks.

Any idea?

       let mut cursor =  coll.find(Some(doc.clone()), None).unwrap();

        for result in cursor {
            if let Ok(item) = result {
                if let Some(&Bson::String(ref username)) = item.get("username") {
                    println!("username: {}", username);
                }
            }
        }

**Comment by kyeah** [comment]
Hey @cedricve! Could you provide a few details on how your database/collection is set up? Is this with a basic, unsecured, single-instance DB? What do your documents look like? How large is your collection? What system/mongodb version are you running on? 

That should help us debug where and how the program is getting locked. Thanks!

**Comment by cedricve** [comment]
hey @kyeah,

Well this is a trivial database with no sharding or authentication. Documents are max (2level nested) and there are about 2000 documents in the collection. Version is db version v3.4.5. Machine is running Ubuntu 16.04.2 LTS.

**Comment by saghm** [comment]
Hi @cedricve! Sorry for the late response; is there any chance you could provide us with some sample database contents that cause the issue? I know it might be tough if you can't give us the exact contents due to them being sensitive, but having a way to reproduce the issue would go a long way towards helping us debug it.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!
