### ISSUE TITLE
Client::connect does not return errors when it cannot connect

### ISSUE THREAD

**Issue by Trolldemorted** [mongodb-labs/mongo-rust-driver-prototype#243]
The following code does not panic:
```
use mongodb::Client;
use mongodb::ThreadedClient;
use mongodb::db::ThreadedDatabase;
fn main() {
    let client = Client::connect("A.B.C.D", 27017).unwrap();
    println!("success!");
}
```

even if there is no host A.B.C.D available on my network. I assume that it should, because connect should return an error if it cannot connect.

mongodb = "0.3.7"
rustc 1.21.0 (3b72af97e 2017-10-09)
toolchain stable-x86_64-pc-windows-msvc

**Comment by saghm** [comment]
Hi @Trolldemorted! To go into more detail, all of the official MongoDB drivers follow [a set of specifications](https://github.com/mongodb/specifications), so we opted to follow them as well despite this being an unofficial driver. For various reasons, the specifications dictate that no actual I/O should be done during the initial connection to the database and that errors should occur lazily rather than eagerly. Given that our Client object is essentially a heavy-weight wrapper around `std::net::TcpStream` (which uses the method name `connect` for its constructor) and that several other drivers use the same name for their constructors, we named our constructor `connect` as well.

I'm noticing now that we don't actually document this behavior in the driver (despite it coming up before in #166), so I think that we should add a line to the documentation for `Client:connect` indicating that this is expected behavior. Any objections @kyeah?

**Comment by kyeah** [comment]
That sounds like a good action for this, @saghm 👍

**Comment by Trolldemorted** [comment]
Thanks for the quick reply!

TcpStream does actually connect when you call connect, doesn't it? You might want to rename connect (::new?), because a connect function that does not connect is a bit counter-intuitive. But yeah, changing the doc is also ok.

But why does it return a result? Can the result ever be Err, if it does not actually connect?

**Comment by kyeah** [comment]
TcpStream connects up front, but we have an internal connection pool that doesn't initiate any streams until it's needed by a request. 

Instead, `Client::connect` can return an error if the configuration is invalid, e.g. the described topology does not match the connection string that is given. These errors arise here: https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/master/src/topology/mod.rs#L851.

**Comment by Trolldemorted** [comment]
Ah, that makes sense!

You might want to update your documentation though, as right now it does not mention when connect will return errors.

**Comment by saghm** [comment]
Thanks for the feedback! When I open a PR with the changes, do you want me to ping you to take a look at it?

**Comment by Trolldemorted** [comment]
Sure, will do!
