### ISSUE TITLE
Don't include (Bulk)WriteExceptions in Ok portion of Results.

### ISSUE THREAD

**Issue by thedodd** [mongodb-labs/mongo-rust-driver-prototype#244]
The following objects have optional error fields which must be evaluated under a success branch as opposed to being propagated as the `Err` variant of the `Result` object which they are always found in. These are always a `WriteException` or `BulkWriteException`.
- https://docs.rs/mongodb/0.3.7/mongodb/coll/results/struct.InsertOneResult.html
- https://docs.rs/mongodb/0.3.7/mongodb/coll/results/struct.InsertManyResult.html
- https://docs.rs/mongodb/0.3.7/mongodb/coll/results/struct.DeleteResult.html
- https://docs.rs/mongodb/0.3.7/mongodb/coll/results/struct.UpdateResult.html
- https://docs.rs/mongodb/0.3.7/mongodb/coll/results/struct.BulkWriteResult.html

Upon a cursory review of the structure of this library, I am of the opinion that these should be moved out of their respective structs enumerated above, and simply returned as the `Err` variant of the operation which they occur in. This will allow for a clean separation of error and success handling, whereas now errors must be evaluated under both branches.

They already have representation in the [Error enum](https://docs.rs/mongodb/0.3.7/mongodb/error/enum.Error.html), as `WriteError(WriteException)` & `BulkWriteError(BulkWriteException)`.

**This would constitute a backwards incompatible change, maybe it should be scheduled for `1.0`. EDIT: or as part of the `0.4` effort, as @kyeah suggested below.**

Perhaps there is some significant reason as to why this design was chosen, and I have merely overlooked it. I am curious as to what that is, if such is the case.

Lastly, outstanding work on this library overall! 👍  This has enabled the creation of the [wither ODM](https://github.com/thedodd/wither) which I have been working on.

**Comment by saghm** [comment]
Hi @thedodd! Offhand, I have no idea why the first four have that field. `BulkWriteResult` is supposed to have it according to [the spec](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst); since MongoDB doesn't currently have transactions, each write in a bulk write is executed separately, so it's possible that one or more writes might succeed before an error occurs. The idea behind the API was that the outer `Result` would be an error if _no_ writes successfully occurred and that the `BulkWriteResult` would contain an error if some writes occurred before an error, but I agree that this is somewhat confusing and not at all ergonomic. I think it would be acceptable to remove the outer Result from the API for `bulk_write` and document that users must check the inner error field; although it would be inconsistent with other CRUD operations, `bulk_write` is semantically a different type of operation from the others, so making it stand out from the more standard operations would arguably be a good thing.

@kyeah, any idea why the non-bulk results have an error field on them? The spec doesn't say anything about this, [nor does there seem to be any change listed about this](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#id30), and I can't find anything in the git history about this since we first started work on the driver. The only thing I can think of is consistency with `bulk_write`, but as mentioned above, I don't think making `bulk_write` consistent with typical CRUD operations is worth making the API less ergonomic. Assuming you don't have any additional insight on this, any objection to removing this field in these four result structs and/or the aforementioned change to the return type of `bulk_write`?

**Comment by kyeah** [comment]
Here's the relevant PR that introduced these: #71. They were initially added to follow the mongo shell behavior, but I'd like to look into this a little more and see if this is still a desired behavior for drivers (or if this is even the behavior for the mongo shell now).

**Comment by thedodd** [comment]
An additional item I forgot to mention, and which is actually the reason for this issue; when I was building this code: https://github.com/thedodd/wither/blob/master/src/migration.rs#L120-L134 I was getting unexpected results where the `update_many` call wasn't returning a top-level error, but there was a nested `write_error`. 

So, an overarching question then: wouldn't the handlers here, which do need to be aware of `WriteException` & `BulkWriteException`s, simply be able to detect the presence of the error and then propagate that as an error for the `Result` of the overall function call?

I am tempted to say that the code here in [`coll.bulk_update`](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/master/src/coll/mod.rs#L850-L860) could be updated such that when it checks for the presence of a write exception, if it detects that one exists, it could just be returned as an `Err(_)` variant. **This would be a breaking change, of course.** But worth discussing, IMHO.

**Comment by kyeah** [comment]
Hey @thedodd, sorry for the radio silence! After looking into the mongo shell behavior, it looks like a BulkWriteException is thrown if any write error is found — as seen [in this example](https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#unordered-bulk-write).

I think your observations above are valid, especially given the behavior seen in the example — we should be propagating the bulk-write exception up as an `Err(_)` variant here. This is a breaking change, but since we are still in a prototype stage and have an explicit instability warning in our readme, we should move forward with this change for v0.4.0 (not quite semver-compliant, but most rust libs don't seem to be 😅).

Would love to see an outside contribution here if you want to take this on — let us know!

**Comment by thedodd** [comment]
@kyeah sorry for the radio silence as well `:)`. Since the time we all had this conversation, the rust ecosystem has grown and matured significantly. I'm stoked about the futures & tokio ecosystem stabilizing so much as it opens up opportunities for more futures based libs to come about (**which is a complete aside from this thread `;)`**).

I would love to get more involved with this library. @kyeah & @saghm, perhaps we should assign a `0.4` label to this issue, and create a new milestone for getting a 0.4 release created.

Thoughts?

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
