### ISSUE TITLE
Support for DNS Seedlist Connection Format, default for MongoDB Atlas

### ISSUE THREAD

**Issue by qguv** [mongodb-labs/mongo-rust-driver-prototype#248]
DNS seedlist connection strings are introduced in 3.6 as described [here](https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format), and are now the default connection string format provided by Atlas. Unfortunately, they're not yet supported in the Rust driver.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
