### ISSUE TITLE
No cursor found for cursor operation.

### ISSUE THREAD

**Issue by thedodd** [mongodb-labs/mongo-rust-driver-prototype#251]
Attempting to [list_indexes](https://docs.rs/mongodb/0.3.7/mongodb/coll/struct.Collection.html#method.list_indexes) on a collection which does not exist, seems to return a [`CursorNotFoundError`](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/980b47ea73053d2135b316c3db93df1c2ea0f672/src/error.rs#L192).

I do not recall this being the case in `0.3.0`, and the `mongo` shell does not return errors under such circumstances. I've tested and verified that this behavior takes place on version `0.3.2` – `0.3.7` (wasn't able to test anything older than that due to a yanked version of the `chrono` lib ... well it would have been more effort than it was worth `;)` anyway).

The only workaround that I am seeing right now is to issue a [create_collection](https://docs.rs/mongodb/0.3.7/mongodb/db/trait.ThreadedDatabase.html#tymethod.create_collection) command before requesting indexes. Thoughts?

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
