### ISSUE TITLE
support async operations

### ISSUE THREAD

**Issue by Trolldemorted** [mongodb-labs/mongo-rust-driver-prototype#253]
It would be great if a variant of insert/update/find would return a [future](https://docs.rs/futures/0.2.1/futures/prelude/trait.Future.html), so that we can efficiently execute a batch of operations on an executor (and its threadpool).

**Comment by thedodd** [comment]
@saghm | @kyeah, you guys have any plans on cutting this crate over to a futures based interface? It would be awesome to get a milestone in place with, perhaps, some issues which folks could start hacking on. 

The nice things about rust futures is that you only need the futures based API. Folks that are not using an async model will still be able to use it in a sync fashion with the `.wait` method and such. So we could evenly cover both bases.

**Comment by thedodd** [comment]
Async/await is stabilizing, and we now have the core Future traits in std. May be a good time to move things in that direction. 

The great thing about a futures based API is that this library would not need to use a reactor itself. It would only have to work with futures. The code that uses this library would then need a reactor in order to drive everything asynchronoously. Or just `.wait()` to use it synchronously. 

Should be able to cover async & sync use cases in one lib.

**Comment by Trolldemorted** [comment]
The [documentation ](https://doc.rust-lang.org/beta/std/future/index.html)states it is experimental:
>This is a nightly-only experimental API. (futures_api #50547)

**Comment by thedodd** [comment]
Indeed. An experimental branch on our side may do the trick though. We could get a stabilization path planned out for it as well.

The other thing that we will need to wait for is the tokio crate to have a version compatible with futures 0.3 (which is the compatibility version with the std futures). Last report I read, the networking wg will be tackling that soon. 

I only mention the tokio crate because that is probably the most logical choice for async TCP, for the mongo wire protocol and such.

**Comment by jdemilledt** [comment]
Is there any progress on this issue? Tokio isn't currently updated for `futures` 0.3 AFAIK, but there is `romio`, which is based on Tokio, but with native futures.

**Comment by pimeys** [comment]
Tokio master is moving to futures 0.3 currently. `std::future` will be stable in Rust 1.36.0 and async/await in 1.38.0. 

Is there already some work done for async transport? It should be quite easy to just use futures 0.1 now and convert to futures 0.3 when they stabilize.

**Comment by wysman** [comment]
Any updates ?

**Comment by rumanbsl** [comment]
Now that Async is stable, is there any plan/roadmap to  support async operations

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
