### ISSUE TITLE
How can I know if connection with the database is down ?

### ISSUE THREAD

**Issue by fdubois1** [mongodb-labs/mongo-rust-driver-prototype#255]
I know that Client::connect() doesn't open the connection with the database.  How can I know if the connection is valid ?  I saw  https://docs.mongodb.com/manual/reference/command/ping/ but I don't know how it should be used here.  Is there a way to know if my connection is valid or not ?
Thanks

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
