### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by xdk78** [mongodb-labs/mongo-rust-driver-prototype#259]
OS: Microsoft Windows [Version 10.0.17134.112] x64
Rust 1.28.0 nightly 
cargo 1.28.0-nightly (e2348c2db 2018-06-07)

```
thread '<unnamed>' panicked at 'Failed to insert document.', libcore\option.rs:960:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
I think this issue is same as tokio and hyper lib https://stackoverflow.com/questions/50644880/cannot-recursively-call-into-core-when-trying-to-achieve-nested-concurrency?rq=1.

**Comment by abelsromero** [comment]
I could build it today also on Windows 10 with:

* stable-x86_64-pc-windows-gnu
* nightly-x86_64-pc-windows-gnu
* nightly-x86_64-pc-windows-msvc (rustc 1.29.0-nightly (6a1c0637c 2018-07-23)

Just cloned the repo and run `cargo build`.

**Comment by saghm** [comment]
It seems to me that this was an issue with a specific nightly version of the compiler and no longer is a problem. Any objections to me closing this issue @xdk78?

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
