### ISSUE TITLE
Unable to connecto to Azure Cosmos/MongoDB (Windows 10)

### ISSUE THREAD

**Issue by abelsromero** [mongodb-labs/mongo-rust-driver-prototype#267]
Hi,

Azure offers "compatible" MongoDB as-a-Service in the CosmosDB offering. This is authenticated with a user and a key and uses SSL. All of this is setup in a connection string you get from Azure's admin portal.
I can connect with the Java drivers without problems but with this drivers I get `No servers available for the provided ReadPreference`.

With Java I don't need to tell anything because all information is in the connection_string, with this driver I tried enabling ssl, storing the key in a file and setting the ReadPreference manually...but nothing.

Here is the code:

```rust
    let username = "...";
    let collection = "...";
    let connection_string = "mongodb://USER:KEY@HOSTNAME:10255/?ssl=true&replicaSet=globaldb";

    let ca_file = "C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt";
    let key_file = "C:\\home\\mongo-key.txt";
    let mut options = ClientOptions::with_ssl(ca_file,ca_file,key_file, false);
    options.read_preference = Some(ReadPreference::new(ReadMode::PrimaryPreferred, None));

    let client = Client::with_uri_and_options(connection_string, options)
        .expect("Failed to initialize client.");

    let coll = client.db(username).collection(collection);
    let count = match coll.count(None, None) {
        Err(e) => {
            println!("Error: {}", e);
            -1
        }
        Ok(count) => count,
    };
    println!("Count: {}", count);
```

PS: I also noticed that when using a wrong key, or setting a wrong path to CRT and key files I get the same error.

**Comment by abelsromero** [comment]
Just wondering if there has been any update on this.
I'd als appreciate if someone can point me in the direction to further investigate.

**Comment by thedodd** [comment]
@abelsromero hey, I don't maintain this crate, but I am seeing a similar issue, particularly with a sharded cluster I am using (connecting through a mongos statefulset in a k8s cluster).

I'll report back if I find anything useful.

**Comment by saghm** [comment]
Hello! Sorry for the lack of response. The issue you're having is appears to be due to the driver currently not supporting any options in the connection string beyond the hostname and the port, meaning that the authentication options will not be parsed. This issue has come up before (specifically in https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/205).

That being said, it's worth noting that CosmosDB is not actually MongoDB; none of the official MongoDB drivers support connecting to CosmosDB, so we don't plan to in this driver either. we plan to fix this issue, but we don't plan to add any specific support for CosmosDB beyond anything that applies to actual MongoDB servers.

**Comment by abelsromero** [comment]
> That being said, it's worth noting that CosmosDB is not actually MongoDB; none of the official MongoDB drivers support connecting to CosmosDB, so we don't plan to in this driver either. we plan to fix this issue, but we don't plan to add any specific support for CosmosDB beyond anything that applies to actual MongoDB servers.

👍 Totally agree! The way I see it, Microsoft is the one stating they provide a compatible product and any kind of divergence with offical MongoDB should be fixed on their side. Is just that I have been working with the official Mongo Java driver (and mongoimport/export) for some time without problems and with this I could not login.

**Comment by saghm** [comment]
Thanks for understanding! Unfortunately I don't work on this driver full-time since it's not officially supported by the company, so there are a number of places where it lags behind the Java driver (and other official drivers). Hopefully some day we'll have an officially supported Rust driver!

**Comment by richerarc** [comment]
Hi, I'm currently looking for a way of connecting to CosmosDB (MongoDB). It seems to connect but infinitely hangs. is there any update on this issue?

**Comment by acmorrow** [comment]
@richerarc - CosmosDB is *not* MongoDB, so there is no expectation that our drivers will communicate with it at all, or work correctly if they do communicate.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
