### ISSUE TITLE
Support for MongoDB transactions. 

### ISSUE THREAD

**Issue by thedodd** [mongodb-labs/mongo-rust-driver-prototype#270]
Hey all.

Any plans for implementing support for transactions per the new 4.0 transactions feature?

**Comment by thedodd** [comment]
Looking through the official specs, looks like the [transactions spec is here](https://github.com/mongodb/specifications/blob/master/source/transactions/transactions.rst) and another pertinent spec which the transaction spec builds upon is the [sessions spec](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst) which we will need to have in order first.

We've got an issue open in this repo for implementing the change streams spec as well. I will probably start with that first, as it is a bit more simple, based on my analysis so far.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
