### ISSUE TITLE
upserted_count and upserted_ids don't represent all upserts

### ISSUE THREAD

**Issue by MarvinHannott** [mongodb-labs/mongo-rust-driver-prototype#272]
When doing a bulk_write like this

```rust
let users_bulk: Vec<WriteModel> = users
        .iter()
        .map(|user| WriteModel::UpdateOne {
            filter: doc!{"user_id": user.user_id},
            upsert: Some(true),
            update:
                doc!{"email_address": user.email_address, "user_id": user.user_id},
        })
        .collect();
    let users_result = users_coll.bulk_write(users_bulk, false);
```
the ```users_result.upserted_count``` is 1, regardless of the true number of upserts. Likewise the ```users_result.upserted_ids``` object only holds the id of the first upserted element.
When indeed no upsert happens, the ```upserted_count``` is zero and ```upserted_ids``` is empty.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
