### ISSUE TITLE
Read Concerns and Write majority

### ISSUE THREAD

**Issue by stefano-pogliani** [mongodb-labs/mongo-rust-driver-prototype#278]
Hello,

I was looking at support for `majority` [read](https://docs.mongodb.com/manual/reference/read-concern-majority/) and [write](https://docs.mongodb.com/manual/reference/write-concern/#writeconcern.%22majority%22) concern.

It seems the driver has support for [read modes](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/master/src/common.rs#L11) which I could not find in the [MongoDB documentation](https://docs.mongodb.com/manual/core/read-isolation-consistency-recency/) but not read *concerns* (which were introduced in MongoDB 3.2).

As for write concerns the driver has support for a numeric `w` parameter but does not seem to have support for the `"majority"` or `<tag set>` concerns.

Would there be interest in a PR to support read concerns and extend write concerns?

I would be happy to work on it but it would be likely to include breaking changes (I'm not sure about the read concerns yet but the `w` parameter would need to change from `i32` to - probably - an `enum`).
Would such breaking change be a deal breaker?

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
