### ISSUE TITLE
Complex Queries

### ISSUE THREAD

**Issue by dkoch144** [mongodb-labs/mongo-rust-driver-prototype#287]
Is there a way to use $exists $and $nin in docs? I have a query like this which works with mongodb from the command line

`db.MY_COLLECTION.find({ $and: [{ "configurations.nodes.children.operator": {$exists: false} }, {"configurations.nodes.operator": /OR/}, {"configurations.nodes.match.vflag": true }, { "configurations.nodes.match.v_flag": { $nin: [false] } } ]}).pretty()`

I tried this but rust didn't like $exists or $nin. 

`let mut doc = doc! {
                                    "configurations.nodes.children.operator": {$exists: false} ,
                                    "configurations.nodes.operator": /OR/,
                                    "configurations.nodes.match.v_flag": true ,
                                    "configurations.nodes.match.v_flag": { $nin: [false]},
                                    "configurations.nodes.match.uri": my_string,
                    };`

It gives the error:
error: expected expression, found `$`

Thanks!

**Comment by saghm** [comment]
You still need to wrap the keys in quotes, even if they begin with a `$`. In this case, you need to use `"$exists"` instead of just `$exists`, `"$nin"` instead of just `$nin`, and so forth. Not wrapping keys in quotes is a JS-specific thing; most other languages (including the macro that was written for this in Rust) still require them.

**Comment by dkoch144** [comment]
Thanks @saghm this worked perfectly, I had to substitute my regular expression as well for a quoted expression. Is there another way to do that if I had a complex regex I wanted to match on? Obviously in this example it's trivial and I'm not sure if I need to do it in other cases but just in case.

Thanks again!

**Comment by saghm** [comment]
If you want to match a regex, you can use the [`$regex` query operation](https://docs.mongodb.com/manual/reference/operator/query/regex/).

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
