### ISSUE TITLE
Derive PartialEq on IndexOptions & implement a builder.

### ISSUE THREAD

**Issue by thedodd** [mongodb-labs/mongo-rust-driver-prototype#288]
This is definitely an enhancement request. Looks like it may overlap a bit with #197. Main idea here is to get a builder in place for `IndexOptions` (but having builders for the other types would be super awesome as well, per #197).

Only other thing is to go ahead and derive `PartialEq` on `IndexOptions` and perhaps a few of the other types. This would be awesome for testing and such, especially for code generation.

For reference as to why I am interested in this, feel free to check out thedodd/wither#16.

It is on my short list to go ahead and open a PR for this in this repo, so if you guys (@kyeah & @saghm) think it would be a good idea, I can follow in suit with #197 and use `typed_builder`. Would be a great way to make some progress on #197 overall.

Cheers.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
