### ISSUE TITLE
provide a prelude::*

### ISSUE THREAD

**Issue by karasjoh000** [mongodb-labs/mongo-rust-driver-prototype#300]
Can there be a `use MongoDB::prelude::*` because I have a lot of import statements from MongoDB it will be nice if I can import them all in one use statement.

**Comment by jcdyer** [comment]
I was thinking about this today while using this library.  I'm not sure the prelude should be too extensive, but a few judicious re-exports could help the ergonomics quite a bit.  In particular, importing the `ThreadedClient` and `ThreadedDatabase` traits when doing basic querying is a non-obvious thing that could be quite confusing to new users, especially if they don't have extensive rust experience.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
