### ISSUE TITLE
Load all documents at once instead of getting a cursor

### ISSUE THREAD

**Issue by balthild** [mongodb-labs/mongo-rust-driver-prototype#308]
I have plenty of documents in my collection. Each query would find some of them, of which counts varying from 0 to thousands. If I iterate over cursors, there will be about 1s of latency if about 2000 documents were found, while loading them at once in `mongo` client with `.toArray()` completes almost immediately.

I can set `batch_size` option to a large number, says 2000, to force the cursor to load enough documents. But it will allocate unnecessary memory for those queries which only match few documents.

While some other libraries for MongoDB have something like EagerCursor, how could I do this after #50 was resolved?

**Comment by saghm** [comment]
Hi @balthild! Cursors are the only thing that the MongoDB server will ever return from a query. Under the hood, any eager implementation in another driver would have to do one of the two thing you mentioned, i.e. either specifying a large enough batch size to get all of the results in the first batch or manually issue `getMore` commands to the server to obtain subsequent batches. Realistically, if we implemented an `EagerCursor` to return a vector of results, it would just be implemented as `cursor.into_iter().collect()`.

That being said, my guess is that the latency you're seeing is a combination of a small batch size and the inefficient networking being done by the driver that has since been fixed in https://github.com/mongodb-labs/mongo-rust-driver-prototype/pull/305. We haven't actually done a release since this fix, which is definitely something we need to do. Assuming @kyeah doesn't have any objections, I can push a new version to crates.io with the performance improvements, which I hope will reduce the latency a bit for your use case. If not, I'm unfortunately not sure there's much you can do beyond increasing the batch size, which you'll need to balance between your desire to reduce memory usage and to minimize round trips to the server.

**Comment by balthild** [comment]
Alright, thanks!
