### ISSUE TITLE
Cursor getMore OperationErrors not handled properly.

### ISSUE THREAD

**Issue by thedodd** [mongodb-labs/mongo-rust-driver-prototype#312]
When the cursor is extracting the BSON & CID from a message, it does not appear to be handling certain error conditions properly.

The code here https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/master/src/cursor.rs#L144 is looking for errors under a key `"errmsg"`; however, it looks like certain errors will return the error under the key `"$err"`, such as when the collection was dropped between getMore calls. In such a case, the error looks like this:

`{"$err": "collection dropped between getMore calls", "code": 96}`

I tried to look through the MongoDB specifications, and couldn't find anything definitive on the expected behavior of errors being returned from the server. This behavior is the same on 3.2, 3.4, 3.6 & 4.0.

**Comment by thedodd** [comment]
I seems like a dead simple fix, and I am happy to open the PR for this; however, I'm not sure how often the errors will be under the `errmsg` key vs the `$err` key. Probably just a version issue. We can handle both. Let me know.

**Comment by saghm** [comment]
When we first wrote this driver, 3.0 was the newest version of the server that existed, so it's possible that this is something that changed in 3.2 that we never updated the driver to handle. The code path will only be executed if an error code is present in the command response, so I think it should be safe to just check for both fields and return whichever one is found.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
