### ISSUE TITLE
No servers available for the provided ReadPreference, yet again

### ISSUE THREAD

**Issue by jjgumucio** [mongodb-labs/mongo-rust-driver-prototype#313]
As @saghm asked me to do in #279 , I'm creating a new issue to discuss the problem of getting an authenticated connection to a remote MongoDB service.

The MongoDB service I'm trying to connect to is a MongoDB Atlas.
The cluster has this characteristics:

- **Instance size:** M0 Sandbox (General)
- **Type:** Replica Set - 3 nodes
- **MongoDB version**: 4.0.9

The authentication mechanism used is through `db.auth("user", "password")`.

Here is the code:

```
let mut options = ClientOptions::new();
options.read_preference = Some(ReadPreference::new(ReadMode::Primary, None));
let connection_string = "mongodb://<mongodb-connection-string>";
// Tried connect_with_uri_and_options too.
let client = Client::connect(connection_string, 27017) 
    .expect("Could not parse Database Url");
let db = client.db("admin");
db.auth("<my-username>", "<my-password>").expect("Could not authenticate to DB");
```

**Note:** I have tried various connection strings: including/not username and password, including/not all replica addresses, including/not db to connect, including/not ClientOptions and other attempts. All having the same error: _No servers available for the provided ReadPreference_

Any help, tips, suggestions, useful slaps in the face are welcome!

**Comment by saghm** [comment]
Hi @jjgumucio! Thanks for bearing with me with regards to opening a new issue for this.

One thing that sticks out at me is that you're prefixing `"mongodb://"` in front of your host when calling `Client::connect`. This method is used only for connections where you don't need any custom configuration and just want to pass a hostname and port. I'd expect it to work if you used `with_uri` though, so this might not be the issue given that you mention you've tried that.

I also notice that you're using a 4.0+ server, which defaults to SCRAM-SHA-256 authentication. Unfortunately, this hasn't been implemented yet in this driver, which still only supports SCRAM-SHA-1. I'm actually not completely sure if this will cause an issue or not; the server expects that the driver will specify with authentication mechanisms it supports, but this also hasn't been added either. If it turns out this is the issue, I should be able to add the necessary functionality for the driver to specify this relatively easily.

The final thing that I can think of is that Atlas requires that the driver connections with SSL, which it doesn't look like you're doing here. You'll need to add the `ssl` feature to your `mongodb` dependency in your Cargo.toml (if you haven't already) and then create the ClientOptions instance with [`ClientOptions::with_unauthenticated_ssl`](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/232b661d9d5a0614ddb9b0b766b5945776ae1af2/src/lib.rs#L274-L281) (apologies for the link directly to the code; I still haven't figured out how to get docs.rs to show the documentation for optional features yet).

**Comment by jjgumucio** [comment]
Thanks for the insights @saghm!
I will try the ssl connection option and removing the `mongodb://` protocol specification.

I will come back with any progress or new info I get.

Thanks again!

**Comment by Zauberklavier** [comment]
Are there any updates on this? I'm also getting this error only that mine occurs after around 20h of uptime from within R2d2. I do not call `db.auth()` or run with SSL. I don't have anything specific yet, will try to debug it next week or so.

**Comment by saghm** [comment]
If you're not using auth or running against Atlas, my guess is that the issue you're having is not caused by the same thing (unless it's due to putting `mongodb://` in front of the host without using `with_uri`.

As for `r2d2`, are you using `r2d2-mongodb`? We don't use r2d2 in this crate currently, and we aren't affiliated at all with the `r2d2-mongodb` crate.

**Comment by Zauberklavier** [comment]
I'm not putting `mongodb://` in the host address or using `r2d2-mongodb`. The `r2d2` implementation I have is a very basic one so I don't think it's `r2d2` related. I was wondering if there was a known bug that might have caused this with Mongo 4. I'll keep you updated.

**Comment by davyzhang** [comment]
I think a workable example with connection to atlas including write and read would be extremely helpful.

**Comment by davyzhang** [comment]
@jjgumucio please check your cargo.toml has this line

mongodb = {version="0.3.12",features = ["ssl"]}

here is the reference :https://medium.com/@shnarazk/connecting-mongodb-atlas-from-rust-programs-65e4cbcbd964

**Comment by jjgumucio** [comment]
@davyzhang Thanks for the tip man!

Will check later and come back with the news

**Comment by jjgumucio** [comment]
Ok, did the test again and had the  `{version="0.3.12",features = ["ssl"]}` added to my .toml file and I get the same error.

I think It can be something about MongoDB Atlas?

Thanks for all the input

**Comment by davyzhang** [comment]
I actually wraped all the connection code to a function which is used to unify the local and altas connection method. This setup works fine the the default settings of atlas free tier replica.

```rust
use mongodb::{Client, ClientOptions, ThreadedClient};
pub fn new_mongo_conn(uri: &str, user: &str, key: &str) -> mongodb::Client {
    if user!="" {
        debug!("connect to atlas,{},{},{}",&uri,&user,&key);
        let opts = ClientOptions::with_unauthenticated_ssl(None, false);
        // opts.read_preference = Some(ReadPreference::new(ReadMode::Primary, None));
        let clnt = Client::with_uri_and_options(&uri, opts).expect("connect to mongodb error");
        clnt.db("admin").auth(user, key).expect("wrong user or key");
        clnt
    } else {
        debug!("connect to local");
        Client::with_uri(&uri).expect("connect to local mongodb error")
    }
}```

**Comment by jjgumucio** [comment]
Thanks again @davyzhang!

I tried running your function like this:

`  let db_url = "mongodb://development-tvmgi.mongodb.net/test?retryWrites=true";
    let mongo_client = new_mongo_conn(db_url, "<DB-USER>", "<DB-PASSWORD");
`

And using the full database url including the user and password:

`  let db_url = "mongodb://<DB-USER>:<DB-PASSWORD>@development-tvmgi.mongodb.net/test?retryWrites=true";
    let mongo_client = new_mongo_conn(db_url, "<DB-USER>", "<DB-PASSWORD");
`

But I still get the same error:

> thread 'main' panicked at 'wrong user or key: OperationError("No servers available for the provided 
> ReadPreference.")', src/libcore/result.rs:999:5

**Comment by davyzhang** [comment]
Firstly, your connection string is not in an atlas replica form, you can find it under altas connection section.
Notice: you should use the old format which marked as 3.4 or earlier.

![image](https://user-images.githubusercontent.com/576863/61916936-d9256e00-af89-11e9-920f-fb994a20fcba.png)

looks like 
```
mongodb://xxxxx.mongodb.net:27017,xxxx.mongodb.net:27017,xxx.mongodb.net:27017/yourdbname?replicaSet=Cluster0-shard-0
```

Secondly, please try to change the db "test" to your real db name like "admin" or some db that exists for later authoriaztion.
Like this
```rust
let db_url = "mongodb://xxxxx.mongodb.net:27017,xxxx.mongodb.net:27017,xxx.mongodb.net:27017/product?replicaSet=Cluster0-shard-0"; 
```

**Comment by jjgumucio** [comment]
@davyzhang MY MAN!

That worked! Thank you very MUCH sir!
I can continue the project now...
