### ISSUE TITLE
Old FindOneAndUpdate struct

### ISSUE THREAD

**Issue by phantomxe** [mongodb-labs/mongo-rust-driver-prototype#318]
https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/51154fe609a09a6a5057c94ccd164ab395159431/src/coll/options.rs#L255

https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/#db.collection.findOneAndUpdate
Mongo has a new type "arrayFilters". Could you update the struct?

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
