### ISSUE TITLE
How to set slaveOk with atlas replica set?

### ISSUE THREAD

**Issue by davyzhang** [mongodb-labs/mongo-rust-driver-prototype#320]
When use secondary preferred option with atlas replica, atlas will refuse to run.
```
MONGO_URI=mongodb://<mask>.mongodb.net:27017,mask.mongodb.net:27017,<mask>.mongodb.net:27017/<db_name>?replicaSet=Cluster0-shard-0&slaveOk=true
```
 with read option
```
 opt.read_preference = Some(ReadPreference::new(ReadMode::SecondaryPreferred, None));
```
and query collection get error
```
user is not allowed to do action [find] on [<dbname>.<col_name>]
```

if I remove the opt.read_preference, works fine

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
