### ISSUE TITLE
Is there any way to reconnect the db again?

### ISSUE THREAD

**Issue by davyzhang** [mongodb-labs/mongo-rust-driver-prototype#321]
I've discovered this issue after my program had run for 2 days. It was used to some repetitive reading and updating work every minute. I only connected to mongodb once when the program started.

The connections stopped working and reported error:
```OperationError("user is not allowed to do action [find] on [<db>.<collection>]")```

It's kind of ridiculous because it works fine for at least 24 hours, and all of sudden, my connections were not authorized. One minute before it worked and the next minute, it didn't.

I restarted the program, it worked again. So I guess I need to reconnect the db after some time. 

I couldn't find any method to do that, is there any?

**Comment by davyzhang** [comment]
I've wrapped my client and force it to reconnect by replacing it with a new instance every 24 hours. This method does well in the first couple of days, but today, I find the same error as before. So I guess I should stay with short-term connections. Currently, there's no way to detect long term connection is ok or not.

**Comment by davyzhang** [comment]
The short-term connections are leaking. As described here in #247.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
