### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by moh-abk** [mongodb-labs/mongo-rust-driver-prototype#323]
Does this driver support Schema Validation as described in this article?
https://docs.mongodb.com/manual/core/schema-validation/

I'm unable to find any reference on it for `mongodb::coll::Collection`

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
