### ISSUE TITLE
Does auth() actually works on Mongo 4.2.0?

### ISSUE THREAD

**Issue by leoaion** [mongodb-labs/mongo-rust-driver-prototype#332]
Mongo DB version: 4.2.0

> let client = Client::with_uri("mongodb://localhost:27017/dbname").expect("Failed to initialize client.");
    let db = client.db("dbname");
    match db.auth("username", "password") {
        Ok(_) => println!("auth success"),
        Err(_) => println!("auth fail");
    }
    db.collection("table").aggregate(...

"auth success" is printed, but still reports "command aggregate requires authentication..."

same code works on mongodb 3.6.3, but fails on 4.2.0. why?

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
