### ISSUE TITLE
ClientInner never release

### ISSUE THREAD

**Issue by armersong** [mongodb-labs/mongo-rust-driver-prototype#335]
There is a recursive reference issue with its field `topology.description.servers`. When creating multi ClientInner instance ,  lots of connection and thread can't be release. 
Recursive reference code:
```rust
        // Fill servers array and set options
        {
            let top_description = &client.topology.description;
            let mut top = top_description.write()?;
            top.heartbeat_frequency_ms = client_options.heartbeat_frequency_ms;
            top.server_selection_timeout_ms = client_options.server_selection_timeout_ms;
            top.local_threshold_ms = client_options.local_threshold_ms;

            for host in config.hosts {
                let server = Server::new(
                    client.clone(),
                    host.clone(),
                    top_description.clone(),
                    false,
                    client_options.stream_connector.clone(),
                );

                top.servers.insert(host, server);
            }
        }
```

**Comment by richerarc** [comment]
Hi @armersong, We found this leak a while ago and I fixed it in our [fork of this repo](https://github.com/Devolutions/mongo-rust-driver-prototype). I've made a PR but no ones is merging it. fell free to use our repo instead in your cargo.toml file

**Comment by armersong** [comment]
ok。thanks

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
