### ISSUE TITLE
Document from HashMap

### ISSUE THREAD

**Issue by nkostoulas** [mongodb-labs/mongo-rust-driver-prototype#336]
Is this possible? I haven't managed to find anything in the docs.

**Comment by saghm** [comment]
This is more of the domain of [the BSON library](https://github.com/zonyitoo/bson-rs/) than the driver, but I can give you a brief overview. 

In the simplest case, if you have a `HashMap<String, Bson>`, you can just convert it directly to a document through the iterator API (`hash_map.into_iter().collect()`) because `Document` implements `FromIterator<(String, Bson)>` and `HashMap<K, V>` implements `IntoIterator<Item=(K, V)>`. If your value type is something that can easily be converted to a `Bson` value, e.g. `i32`, you can just add a call to `Iterator::map` and it will work the same way (e.g. `hash_map.into_iterator().map(|(k, v)| (k, Bson::I32(v)).collect()`). If your key type isn't String or you have something more complex as your value type, then it might not be as straightforward as using an iterator API; in that case, using `serde` is probably your best bet, since the `bson` library has built-in support for that.

**Comment by nkostoulas** [comment]
Went with that thanks 👍
