### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by awakecoding** [mongodb-labs/mongo-rust-driver-prototype#337]
I would like to inquire about the mongo Rust driver project status, as it appears that development has stalled for some time, with multiple pull requests waiting to be merged.

We have a pull request opened since March to address a serious issue that we found in production on our side: https://github.com/mongodb-labs/mongo-rust-driver-prototype/pull/304

Somebody else apparently identified the same issue just two weeks ago, because it still isn't fixed on master: https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/335

Issues with circular references causing leaks, and the lack of proper replica set support are becoming a serious issue for us. We use MongoDB in all of our Rust microservices, and we'd need to get things moving.

I found in another pull request a comment regarding the development of a new, official MongoDB Rust driver, dating from September 18th: https://github.com/mongodb-labs/mongo-rust-driver-prototype/pull/302#issuecomment-532677869

Can we expect a public release of this new driver anytime soon, and if not, can we at least get more of the pull requests with good fixes merged in master? This is becoming a critical issue for us, so we'll be investing time trying to fix issues, but it's all wasted if it remains on our own fork while waiting for a completely new Rust driver to come out.

**Comment by saghm** [comment]
Hello @awakecoding! Yes, we have been developing a new driver that will have official status, but I'm not able to give an exact timeline for when it will be released yet. I think it's worth keeping in mind that this driver has been marked as a prototype that shouldn't be used in production since it's initial release, and that has never changed. That being said, I totally understand your frustration with the state of it, and that's exactly why I pushed for us to develop an official driver that we can support for production use.

To answer your specific question, we're close enough to the release of the alpha of the new driver that we don't plan on doing any more releases of the prototype. Once we've released the alpha, I plan on updating the README and adding a comment to all the currently open issues and pull requests to explain that the prototype isn't supported anymore and to link to the new project.

**Comment by awakecoding** [comment]
Hi @saghm, thanks for your reply. I understand that this prototype wasn't meant for production usage, but my understanding is that a lot of people are fine with a no-warranty, community-supported driver as long as they can contributes fixes to it. Since this driver is by far the most advanced, it is likely used by a lot of people, which means probably in production as well.

The major issue that we fixed in https://github.com/mongodb-labs/mongo-rust-driver-prototype/pull/304 prevents leaking database connections, especially if used with a connection pool. We found out the hard way about this problem because of crashes at regular intervals after some of our microservices reached over 4000 leaked database connections. I would at least merge this one in the current Rust driver to spare this pain to other people.

In the meantime, we are actively working on tracking the source of a slow but steady ~2MB per hour memory leak in our microservices that use this driver. This is a critical issue for us because this leaks causes a memory increase of ~336MB per week, meaning we have to pre-emptively restart our microservices before they go out of memory. Since we are time constrained (we can't just watch our microservices leak until they die) the quickest solution would be to fix the current driver as well, and prepare a pull request.

I know there is a much better, shinier driver coming up, but I don't want to put pressure into shipping it faster. The least I would ask is to accept pull requests on the current one until the new one comes out, because we have no choice but to patch the current one at this point in time.

**Comment by moh-abk** [comment]
@saghm can you at least provide a timeframe for the alpha release? Late 2019? First quarter 2020?

**Comment by saghm** [comment]
We expect to release within the next couple months, but potentially a lot sooner than that

**Comment by Igosuki** [comment]
Cargo makes it easy enough to build your own version of the repo. I know this can feel risky, but the codebase is small enough.

**Comment by awakecoding** [comment]
Just a quick update on our status and intentions:

1) We found and fixed the ~2MB/hour memory leak (https://github.com/Devolutions/mongo-rust-driver-prototype/pull/1). Our microservices had to reboot every week or so because of that.
2) We are actively working on getting replica sets supported in the current driver, allowing us to move our single instance database to something much better like MongoDB Atlas.

Last but not least, we intend to maintain and publish our fork until the new official Rust driver is released and stabilized. Since there is no intent to maintain the current driver, we'll take this responsibility and publish our own patched version. This should be a short-lived fork, but at least there will be a more stable option available in the meantime.

**Comment by Bajix** [comment]
@saghm I take it part of the wait for this was for the release of async await in stable? The new version is going to be feature complete and work with 4.2?

Just out of curiosity, but has the MongoDB team looked into using Rust for any parts of the DB?

**Comment by saghm** [comment]
Not exactly; the initial release of the driver will be synchronous because that's all that was available when we started working on it. That being said, one of the reasons it took so long was that we spent a lot of time making sure the driver is architecture in a way that will support all the features we need going forward (both MongoDB features like sessions and retryable reads/writes and Rust features like async) needing to drastically refactor or break API. We also spent a lot of time on things like the SDAM, the system the driver uses to track the topology of the cluster a client is connected to, because historically, drivers (including the prototype Rust driver, but also a few of the drivers in other languages) have had subtle bugs in their implementations. The initial alpha release will not be feature complete, but we'll be working to add the remaining features immediately after the release, starting with switching the driver to async (although we well still maintain the existing sync API, just as a wrapper around the async one).

I don't know of any initiatives to use Rust in the server; my general understanding is that due to the codebase being in C++ since long before Rust was a viable option, it's simpler to continue using a single language for new features. Although personally I think Rust would be an excellent choice for a new database being written from scratch, I certainly don't think it's worth rewriting the entire server codebase, and I sympathize with concerns about adding a new language to an existing codebase that would otherwise be homogeneous; some of the same reasons for making a fully native Rust driver instead of wrapping the C driver could be applied in favor of keeping the server codebase all in one language, and I still feel strongly that a fully native Rust driver is the right decision.

**Comment by Bajix** [comment]
I think you should consider abandoning the idea of ever releasing a sync version in the first place, and instead go the route of building towards a feature-complete async-only API as the initial release. This will greatly simplify documentation and maintenance for one, as well as prevent refactoring pains later. You're in a fairly great position to make dramatic breaking changes right now before this is released. I would say the biggest holdup right now that is preventing many companies from going all in on Rust serverless microservices is the lack of async driver support. There being a full async MongoDB official driver would be a really big deal; the same is true of Diesel. If you can make an async driver happen sooner by skipping the release of the in-progress sync driver, that's a worthwhile trade.

**Comment by saghm** [comment]
Thanks for the feedback! We're close enough to the initial release of the driver that skipping an initial sync release won't really change the timeline at all; either we do a sync release really soon and follow up some time later with async support, or we don't release anything now and the same amount of time later we release an async driver.

Not having any sort of synchronous API also isn't really an option for us. The overwhelming majority of MongoDB users are used to using synchronous drivers, so having such an API will make it significantly easier for users of other drivers to try out the Rust driver. Offering a sync API also won't really increase the maintenance burden; we plan on having the driver internals be 100% async and just have the sync API be a 1:1 mapping of the async one where each sync method simply blocks on the async equivalent. Short of a breaking API change (which we obviously won't be doing outside of major version updates once we hit 1.0, and we hope not to have to do many of them before then either), there wouldn't really be any need to ever touch those implementations, especially if we use some sort of macro to generate them.

**Comment by Bajix** [comment]
Ah; so long as the driver internals are 100% async that'll make it far easier to support both async and sync. The question though is then why not release both the async and sync API's at the same time? At that point you've already created an async API and the sync API is just the async API wrapped with a runtime helper function to block on a future. 

That approach to separating them sounds good; that way it's the same API and the upgrade path could be as simple as using the async version instead, adding async/await keywords and adding a runtime annotation.

**Comment by saghm** [comment]
We don't currently have the async version implemented, but we do have everything we want besides a couple of small things to make it easier for users to connect to Atlas (a common pain point with the prototype) already implemented synchronously, which is why we're going to release that first. The very first thing we'll work on after the initial release is updating everything to be async, but there's no reason not to release the working product that we already have, which will alleviate a large number of user issues with the prototype immediately rather than some indeterminate amount of time later. Additionally, myself and other members of the team will all be taking various amounts of vacation time over closer to the end of the year, so if everything works out, we can start async right after we're all back.

From some basic experimentation, I think that 85-90% of the driver code can just be converted like you said (adding async to the function signatures and adding await to async function calls). There are a couple of tricky points though, specifically related to where the driver users background threads to perform work like keeping track of the cluster's topology and managing connections in the connection pools for each server. Given that both of those areas are places where subtle bugs have been uncovered in other async MongoDB drivers, we don't want to rush the design of those parts.

**Comment by saghm** [comment]
Hello everyone! We've just released the alpha of [the official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
